name: Branches
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
concurrency:
  group: branches-${{ github.ref_name }}
  cancel-in-progress: false
jobs:
  coverage:
    name: Coverage
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@fd29bf3c58b72faacc300e068a05b59eb3b180bc # 0.10.1
    with:
      source_branch: ${{ github.ref_name }}
      enable_unit_tests: false
      enable_integration_tests: false
      enable_unit_coverage: true
      unit_coverage_command: "nix run .#coverage-unit"
      runner_unit: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
