################################################################################
# Main pipeline to build the artifacts
################################################################################
name: Build
on:
  merge_group:
    types: [checks_requested]
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - synchronize
permissions:
  contents: write
  actions: write
  security-events: write
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-build
  cancel-in-progress: true
jobs:
  docs:
    name: Docs
    uses: ./.github/workflows/build-docs.yaml
    secrets: inherit
    with:
      source_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      publish: false
  library:
    name: Library
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 30
    if: github.event.pull_request.draft == false
    env:
      CI: "true"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          persist-credentials: false
      - name: Build the workspace
        run: |
          nix develop -c cargo build
