#################################################################################
# Child pipeline to cache the dependencies
#################################################################################
name: Cache dependencies
env:
  RUST_BACKTRACE: "1"
on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string
concurrency:
  group: ${{ inputs.source_branch || github.ref_name }}-cache-deps
  cancel-in-progress: true
jobs:
  cargo:
    runs-on: depot-ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ${{ inputs.source_repo }}
          ref: ${{ inputs.source_branch }}
          persist-credentials: false
      - name: Replace the crates.io registry with a private proxy registry
        env:
          PRIVATE_CARGO_REGISTRY_PROXY_URL: ${{ secrets.PRIVATE_CARGO_REGISTRY_PROXY_URL }}
        run: "cat >> .cargo/config.toml<< EOF        \n[source.hopr-cargo-registry-cache]\nregistry = \"sparse+${PRIVATE_CARGO_REGISTRY_PROXY_URL}\"\n    #magic___^_^___line\n[source.crates-io]\nreplace-with = \"hopr-cargo-registry-cache\"\nEOF\n    #magic___^_^___line\n"
      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: hoprnet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        env:
          USER: runner
      - name: Cache dependencies
        run: |
          nix develop -c cargo fetch
