#################################################################################
# Pipeline triggered on every pull request to run unit and smoke tests
#################################################################################
name: Test
env:
  RUST_BACKTRACE: "1"
  FOUNDRY_PROFILE: ci
on:
  merge_group:
    types: [checks_requested]
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-${{ github.workflow}}
  cancel-in-progress: true
jobs:
  tests-unit:
    name: Unit Tests
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    env:
      CI: "true"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          persist-credentials: false
      - name: Run unit tests
        run: nix build -L .#hopr-test
  tests-unit-nightly:
    name: Unit Tests Nightly
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    if: github.event.pull_request.draft == false
    env:
      CI: "true"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          persist-credentials: false
      - name: Set up Google Cloud Credentials
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        if: ${{ !env.ACT }}
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      - name: Run unit tests nightly
        run: |
          nix build -L .#hopr-test-nightly
  tests-smart-contracts:
    runs-on: self-hosted-hoprnet-bigger
    name: Smart Contracts
    timeout-minutes: 60
    if: github.event.pull_request.draft == false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          persist-credentials: false
      - name: Set up Google Cloud Credentials
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        if: ${{ !env.ACT }}
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      - name: Run tests
        run: nix develop -L -c make -j smart-contract-test
        env:
          HOPR_NETWORK: anvil-localhost